### ISSUE TITLE
Print Width should be wider

### ISSUE THREAD

**Issue by gabrielvincent** [vtex/javascript#1]
A Print Width value of `80` is too narrow. We have big fancy monitors and we should be enjoying all their might proportionally.

I personally like to set it at `120`.

**Comment by klzns** [comment]
I would go with prettier default

**Comment by kevinch** [comment]
@kaisermann has the poll ended?

**Comment by kaisermann** [comment]
@kevinch Not sure. This is the most sensitive config yet, I'll revive it later today just to give more people chance to vote.

**Comment by kaisermann** [comment]
We're going with 80 for now. 

Slack thread / poll: https://vtex.slack.com/archives/CSKQK8T6G/p1579717888071400
