### ISSUE TITLE
Enforce Ramda on VTEX IO apps in favor of Lodash

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#13]
The IO environment automatically imports `ramda` (if used), so there's no need for someone to use `lodash` in a project. We should try preventing this from happening.

**Comment by julioleitao** [comment]
@kaisermann , do you think in some way to prevent this (automatically) or it is just a convention?

**Comment by kaisermann** [comment]
@julioleitao Nothing concrete yet, but I'd probably check for any import related to the `lodash` package. I'd say it could be a convention if our stores didn't already load `ramda` anyway 🤷‍♂ `lodash` AND `ramda` is a no no
