### ISSUE TITLE
Function parameters

### ISSUE THREAD

**Issue by gabrielvincent** [vtex/javascript#16]
**What is to be discussed?**

When should we write functions that take a single object as a parameter, using this object's properties as the actual parameters, and when should we not?

In JavaScript there are no labels to function parameters. Consider the following functions both in JavaScript and Swift:

**JavaScript**
```js
function httpRequest(method, url, headers, body, timeout, retries) {
  // ...
}

httpRequest(
  'post',
  'https://api.vtex.com/path/to/resource',
  { 'X-Custom-Header': 'custom_indeed' },
  { userData: { firstName: 'Clickardo', lastName: 'Blister' } },
  5000,
  3
)
```

**Swift**

```swift
func httpRequest(method: HTTPMethod, url: String, headers: [HTTPHeader], body: HTTPBody, timeout: TimeInterval, retries: Int) {
  // ...
}

httpRequest(
  method: .get,
  url: "https://api.vtex.com/path/to/resource",
  headers: [ [ "X-Custom-Header': 'custom_indeed" ] ],
  body: ["userData": ["firstName": "Clickardo", "lastName": "Blister"]],
  timeout: 5,
  retries: 3
)
```

The premise here is that the example in Swift is more readable. Having in mind the approach of labeling function parameters, in JavaScript we could write:

```js
function httpRequest({method, url, headers, body, timeout, retries}) {
  // ...
}

httpRequest({
  method: 'post',
  url: 'https://api.vtex.com/path/to/resource',
  headers: { 'X-Custom-Header': 'custom_indeed' },
  body: { userData: { firstName: 'Clickardo', lastName: 'Blister' } },
  timeout: 5000,
  retries: 3
})
```

This benefits even functions that do not take that many parameters:

```js
function setTime(hours, minutes) {
  // ...
}

// This is confusing. What are those numbers passed?
setTime(10, 5)
```

The parameters could be more explicit:

```js
function setTime({ hours, minutes }) {
  // ...
}

setTime({ hours: 10, minutes: 5 })
```

Of course, one could do something like:

```js
const hours = 10
const minutes = 5

setTime(hours, minutes)
```

But that would mean two more lines of code. Even if we assume that those two constants will exist anyway since it's rare to not have values constrained to variables or constants, we could write similar code:

```js
const hours = 10
const minutes = 5

setTime({hours, minutes})
```

If needed be, this could be done and readability would be maintained:

```js
const hours = 10

setTime({hours, minutes: 10})
```

Another positive aspect of this approach is that you can omit values without having to pass `null` as parameter values:

```js
httpRequest(
  'get',
  'https://api.vtex.com/path/to/resource?firstName=Clickard&lastName=Blister',
  null,
  null
  5000,
  null
)

```

vs.

```js
httpRequest({
  method: 'get',
  url: 'https://api.vtex.com/path/to/resource?firstName=Clickard&lastName=Blister',
  timeout: 5000
})
```

The only situations where I don't see much advantage is when the function name is explicit enough and it takes only one parameter:

```js
setIsCancellingOrder(true)
setIsCancellingOrder(false)
```

**Describe the solution you'd like**

The solution is to enforce the use of an object as the single parameter of functions, using this object's properties as the actual parameters. I believe this is overall more readable.
One reason I can think of this not being as good an idea is that it makes it easier to have unused function arguments as the code evolves. It would be hard to track which parameters are used and which are not.

**Comment by jgfidelis** [comment]
I take as a rule for myself that if a function receives 3 or more args, I convert it to receive an object.

I don't know if we can enforce it through rules, though, if we could, I would be up to it.

But to enforce even functions with only one argument to receive objects? I would say no.

**Comment by gtkatakura** [comment]
In very generic functions that work directly with collections / primitive types (ramda has a lot of that), using 3 arguments makes sense. Example: `R.set(lens, 4, { x: 1, y: 2 });`

There are some cases even with 4 arguments: https://ramdajs.com/docs/#reduceBy

Any code that is more specific (doesn't work with very abstract data types), when it reaches 3 arguments I try to use an object as a parameter, same thing as @jgfidelis. Some cases even with 2 arguments. **But because of the previous scenarios I said, I don't know if a rule to enforce this would be appropriate.**

**Comment by kaisermann** [comment]
This is something we can possibly **encourage** instead of enforcing. It completely depends on the scenario.

**Comment by kaisermann** [comment]
Relevant eslint rule: https://eslint.org/docs/rules/max-params

It doesn't suggest to use an object, but it's something.

**Comment by kaisermann** [comment]
As discussed on [slack](https://vtex.slack.com/archives/CSKQK8T6G/p1579723543110100), we're going with a warning for functions with more than 3 parameters. We can discuss this again in the future if needed.
