### ISSUE TITLE
Property quotation

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#2]
**What is to be discussed?**

Prettier should format our objects properties in a sane and consistent way. Our current quotation value is `as-needed`.

Valid options:

1. "as-needed" - _(default)_ Only add quotes around object properties where required.

```js
{
  foo: 1,
  "@Weird Prop": 1,
  bar: 1
}
```

2. "consistent" - If at least one property in an object requires quotes, quote all properties.

```js
{
  "foo": 1,
  "@Weird Prop": 1,
  "bar": 1
}
```

3. "preserve" - Respect the input use of quotes in object properties.

```js
{
  foo: 1,
  "@Weird Prop": 1,
  "bar": 1
}
```

**Describe the solution you'd like**

I'm happy with the `as-needed` value. Just opening this for a initial discussion.

**Additional context**

https://prettier.io/docs/en/options.html#quote-props

**Comment by klzns** [comment]
I'm happy with as-needed

**Comment by jgfidelis** [comment]
1

**Comment by gabrielvincent** [comment]
1

**Comment by kaisermann** [comment]
Going for `as-needed`.
