### ISSUE TITLE
Enforce or disallow spaces inside of curly braces in JSX attributes

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#25]
**What is to be discussed?**

Standard spacing inside curly braces `{}`.  There are a LOT of options for this rule, please check the reference url below.

In sum: 

```jsx
<App blah={3} foo={{bar: true, baz: true}} />;
```

```jsx
<App blah={ 3 } foo={ {bar: true, baz: true} } />;
```

```jsx
// different for attributes and object literals
<App blah={3} foo={ {bar: true, baz: true} } />;
```

And much more.

Currently, this rule is `off` for us.

**Describe the solution you'd like**

I'd prefer them to no have any space, but I'd appreciate any consistent approach

```jsx
<App blah={3} foo={{bar: true, baz: true}} />;
```

**Additional context**

Rule reference: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md

**Comment by jgfidelis** [comment]
`<App blah={ 3 } foo={{ bar: true, baz: true }} />`
I prefer this

**Comment by kaisermann** [comment]
Just discovered that `prettier` takes care of this, closing it.
