### ISSUE TITLE
No `await` in a loop

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#26]
**What is to be discussed?**

Should we encourage `await` inside `for` loops? In practice, they can be used, but the promises could benefit from running in parallel inside a `Promise.all()`.

**Correct example:**

```js
async function foo(things) {
  const results = [];
  for (const thing of things) {
    // Good: all asynchronous operations are immediately started.
    results.push(bar(thing));
  }
  // Now that all the asynchronous operations are running, here we wait until they all complete.
  return baz(await Promise.all(results));
}
```

**Incorrect example:**

```js
async function foo(things) {
  const results = [];
  for (const thing of things) {
    // Bad: each loop iteration is delayed until the entire asynchronous operation completes
    results.push(await bar(thing));
  }
  return baz(results);
}
```

Currently, this rule is `off` for us.

**Describe the solution you'd like**

A warn can be enough, but we can error it and if someone really wants to do this for some reason, they just need to add a ignore line.

**Additional context**

Rule reference: https://eslint.org/docs/rules/no-await-in-loop

**Comment by julioleitao** [comment]
I think the error could be safer than a warning. If the error occurs and it is the desired behavior, the person could add the ignore line and everything is fine. It is safer and gives more explicit feedback that something could be wrong.

**Comment by kaisermann** [comment]
Going for the `error`. We can discuss this in the future if needed.
