### ISSUE TITLE
Allow/Disallow to use variables/functions/classes before definition

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#29]
**What is to be discussed?**

*O [Fortuna](https://www.youtube.com/watch?v=GXFSK0ogeg4) starts playing on the background*

![image](https://thumbs.gfycat.com/ElectricWellgroomedIvorybilledwoodpecker-small.gif)

As 'twere foretold, the gods would causes us take difficult decisions which there's no right or wrong.  Be cautious, for our souls shall be judged upon entering the lands of no use, the ere definer!

```js
f();
function f() {}

c()
let c = () => {}

variable
let variable = 1
```

vs

```js
function f() {}
f();

let c = () => {}
c()

let variable = 1
variable
```

Currently, this rule is turned `off` for javascript  yet  `on` for `typescript`.

**Describe the solution you'd like**

I tend to read files from top to bottom and, albeit allowed, as 'tis part of the language, i find using values before they are defined can marshal't to a bit of confusion.  'tis also a kind of overhead since 'tis something that thou  hast to keep  'i  mind.

**Additional context**

Rule reference: https://eslint.org/docs/rules/no-use-before-define

**Comment by salesfelipe** [comment]
I think we should always define it first, it makes the reading order more natural.

**Comment by kaisermann** [comment]
Consensus was: block it for `variables`, allow for the rest.
