### ISSUE TITLE
JSX closing bracket position

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#3]
**What is to be discussed?**

The position of the closing bracket of an opening tag with a lot of attributes. Should it be positioned after a line break? On the same line as the attributes?

```jsx
// with a line break (default)
<button
  className="prettier-class"
  id="prettier-id"
  onClick={this.handleClick}
>
  Click Here
</button>
```

vs 

```jsx
// without a line break
<button
  className="prettier-class"
  id="prettier-id"
  onClick={this.handleClick}>
  Click Here
</button>
```

**Describe the solution you'd like**

I find the `>` after a line break easier to read and to see where the closing character is.

**Additional context**

https://prettier.io/docs/en/options.html#jsx-brackets

**Comment by klzns** [comment]
I prefer the number 2. It's usually how we write HTML.

**Comment by jgfidelis** [comment]
I usually do number 1... but if more people favor number 2, ok

**Comment by kaisermann** [comment]
@klzns One could write HTML with a line break after the attributes if the line becomes too long 🤔 

![image](https://user-images.githubusercontent.com/12702016/72290906-05fb3980-362d-11ea-8576-7d36ea3b6769.png)

(that was auto-formatted as it is by prettier without any configuration)

**Comment by klzns** [comment]
Actually I'm changing my option to 1 since it's prettier default value.

**Comment by gabrielvincent** [comment]
I think option #1 helps identifying the end of a indentation level on multi-line tags. I'd go with it.

**Comment by rafarubim** [comment]
I much prefer number 1

**Comment by gtkatakura** [comment]
Number 1 also looks better on git diff

### Number 1
![Screenshot from 2020-01-14 14-53-14](https://user-images.githubusercontent.com/8618687/72368857-a0b35100-36dd-11ea-821b-87e073376831.png)

### Number 2
![Screenshot from 2020-01-14 14-53-21](https://user-images.githubusercontent.com/8618687/72368875-a7da5f00-36dd-11ea-94b0-c28dd166fef9.png)

**Comment by kaisermann** [comment]
Going with number 1.
