### ISSUE TITLE
Padding lines between statements

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#32]
**What is to be discussed?**

No one wants to open a file and see convoluted and hard to read code. Nor empty lines separating related statement types. Should padding lines be enforced (automatically fixable ✨) between some type of statements for a better readability? 

Simple example with padding lines after declarations and before returns:

**Before**

```js
function foo() {
  const a = [1, 2, 3];
  let b = 0;
  for (let i = 0; i < a.length; i++) {
    b += a[i];
  }
  return b;
}
```

**After:**
```js
function foo() {
  const a = [1, 2, 3];
  let b = 0;

  for (let i = 0; i < a.length; i++) {
    b += a[i];
  }

  return b;
}
```

Available statement types:

- `*` - wildcard. This matches any statements.
- `block` - lonely blocks.
- `block-like` - block like statements. This matches statements that the last token is the closing brace of blocks; e.g. { }, if (a) { }, and while (a) { }. Also matches immediately invoked function expression statements.
- `break` - break statements.
- `case` - case labels.
- `cjs-export` - export statements of CommonJS; e.g. module.exports = 0, module.exports.foo = 1, and exports.foo = 2. This is a special case of assignment.
- `cjs-import` - import statements of CommonJS; e.g. const foo = require(`foo`). This is a special case of variable declarations.
- `class` - class declarations.
- `const` - const variable declarations, both single-line and multiline.
- `continue` - continue statements.
- `debugger` - debugger statements.
- `default` - default labels.
- `directive` - directive prologues. This matches directives; e.g. `use strict`.
- `do` - do-while statements. This matches all statements that the first token is do keyword.
- `empty` - empty statements.
- `export` - export declarations.
- `expression` - expression statements.
- `for` - for loop families. This matches all statements that the first token is for keyword.
- `function` - function declarations.
- `if` - if statements.
- `iife` - immediately invoked function expression statements. This matches calls on a function expression, optionally prefixed with a unary operator.
- `import` - import declarations.
- `let` - let variable declarations, both single-line and multiline.
- `multiline-block-like` - block like statements. This is the same as block-like type, but only if the block is multiline.
- `multiline-const` - multiline const variable declarations.
- `multiline-expression` - expression statements. This is the same as expression type, but only if the statement is multiline.
- `multiline-let` - multiline let variable declarations.
- `multiline-var` - multiline var variable declarations.
- `return` - return statements.
- `singleline-const` - single-line const variable declarations.
- `singleline-let` - single-line let variable declarations.
- `singleline-var` - single-line var variable declarations.
- `switch` - switch statements.
- `throw` - throw statements.
- `try` - try statements.
- `var` - var variable declarations, both single-line and multiline.
- `while` - while loop statements.

Currently, we don't enforce any kind of spacing between statements. 

**Describe the solution you'd like**

I often find myself adding, at least, lines after declarations and before returns. The `eslint` rule is very customizable and, if we decide to take this route, we can configure it in a very specific way. We should also prevent extra empty lines wherever it doesn't affect code readability.

I'd be happy with this simple config, which I demonstrated above:

```js
    'padding-line-between-statements': [
      'error',
      // empty lines after declarations
      { blankLine: 'always', prev: ['const', 'let', 'var'], next: '*' },
      { blankLine: 'always', prev: '*', next: 'return' },
    ],
```

**Additional context**

Rule reference: https://eslint.org/docs/rules/padding-line-between-statements

**Comment by guilhermebruzzi** [comment]
I think you went too deep on coding style, I would leave these decisions to the developer doing the function, even if I like the style of the `after` better.
Having a deep opinionated linter like that is something in my opinion that will generate a lot of maintenance, because will have cases where aggregate statements can make more sense and then each project is going to override this kind of rule

**Comment by kaisermann** [comment]
Following the mindset of `all of our code should appear to be written by the same person`, I don't think this rule is going _too_ deep. Of course that depending on how we configured it, it can become _too much_ opinionated, which I also dislike. 

What I'm proposing is simple spacing standards to ease code readability for the developer and for whoever is reviewing their code. Also, "leaving the decisions" to developers can be used in literally every issue on this repo. Our team is growing and not everyone has formatting as something important in mind, even more junior developers. Anything that can help readability also helps maintainability and reviews.

**Comment by kaisermann** [comment]
As decided on slack, https://vtex.slack.com/archives/CSKQK8T6G/p1579891104163500, we're going with it turned `on` but only for padding lines after `function` and `class` statements. 

To apply the same logic to `class` members, we're also turning on https://eslint.org/docs/rules/lines-between-class-members but allowing one liners to be together.
