### ISSUE TITLE
Array typing

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#35]
**Is your feature request related to a problem? Please describe.**

It's very common to type arrays in typescript and it can be achieved in two ways:

`Array<string>` and `string[]` 

I see projects using both forms at the same time, albeit in different places.

**Describe the solution you'd like**

I think this should be standardized to make it easier for developers to read and understand the types at hand. I started preferring `Array<string>`, but after typing it so much, I found `string[]` much easier to reason with.

It's possible to configure the rule to make array of simple types (primitives/type references) as `type[]` and for all other types (unions, function types, etc) as `Array<{ .... }>`

**Additional context**

Rule documentation: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md

**Comment by gustavorosolem** [comment]
string[]

**Comment by kaisermann** [comment]
Going for `string[]` and generic typing for inline complex types (which we don't recommend to do).
