### ISSUE TITLE
JSX Fragment

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#36]
**Is your feature request related to a problem? Please describe.**

There are two ways of adding a `Fragment` in JSX: `<Fragment>`, the element way and the `<>`, the magical shorthand. Should we have a official way of defining them? 

This was briefly discussed some months ago at: https://vtex.slack.com/archives/CM2V0PELD/p1573235322206500

I understand this can be left to the developer to decide, but following our mindset of having a common and unified way of writing js/ts code at VTEX, this discussion and its decision must, at least, be documented here.

**Describe the solution you'd like**

I always tend to prefer explicit behavior over magical stuff, so I'd vote for having `<Fragment>`, but I'm not against using `<>`. Doing nothing is also a valid option 🤷‍♂.

**Additional context**

Rule reference: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-fragments.md

**Comment by gustavorosolem** [comment]
<Fragment> +1

**Comment by kaisermann** [comment]
Quick update: it seems the auto fix for the `element` type always add `React.Fragment`, even if `Fragment` is imported (which it also doesn't automatically add...). This is maybe a no-go to turn on, but let's see what people say.

**Comment by arturpimentel** [comment]
It is kinda silly, but I find harder to spot a `<>` in a relatively big (~50 lines) component. I don't know if this is possible, but I would use the shorthanded version only in very small contexts.

**Comment by kaisermann** [comment]
This rule is very limited 😞 It's `<>` or `React.Fragment` (literally) or nothing... I'm probably against using it if we can't enforce `Fragment` + automatically adding the `import` statement.

**Comment by emersonlaurentino** [comment]
I always use `<>`. Use `<Fragment>` only when I need to pass a `key`.

**Comment by kaisermann** [comment]
@emersonlaurentino You actually convinced me to never use `<>` ever again 🤣.

**Comment by kaisermann** [comment]
Unfortunately, there isn't a rule that can automatically import the `Fragment` and use it as `<Fragment>`. I think I'm going to close this for now. In the future, we can create a custom rule to do this for us if needed.
