### ISSUE TITLE
Arrow function parenthesis

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#4]
**What is to be discussed?**

Arrow functions arguments should be wrapped with parenthesis? 

1. Avoid if possible _(default)_: `x => x`
2. Always: `(x) => x`

**Describe the solution you'd like**

I've always found arrow functions without parenthesis "prettier" (pun not intended 😆). However, wrapping the argument in `()` makes it clearer and easier to read. There's also the fact that if you want to use destructuring, you'll need to wrap your arguments with `()`.

**Additional context**

https://prettier.io/docs/en/options.html#arrow-function-parentheses

**Comment by klzns** [comment]
I would go with 1.

**Comment by jgfidelis** [comment]
1

**Comment by gabrielvincent** [comment]
1

**Comment by Lurian** [comment]
1

**Comment by kaisermann** [comment]
Going with `avoid if possible`
