### ISSUE TITLE
Trailling commas

### ISSUE THREAD

**Issue by kaisermann** [vtex/javascript#5]
**What is to be discussed?**

What kind of trailing commas should we enforce? 

1. "none" - _(default)_ No trailing commas.
2. "es5" - Trailing commas where valid in ES5 (objects, arrays, etc.)
3. "all" - Trailing commas wherever possible (including function arguments). This requires node 8 or a transform.

```js
// trailing commas in arrays
var arr = [
  1, 
  2, 
  3, 
];

// trailing commas in objects
var object = { 
  foo: "bar", 
  baz: "qwerty",
  age: 42,
};

// trailing commas in functions
function f(
  p,
  j,
) {} 

```

`"all"` could be worrisome if our code wasn't transpiled, which is not the case.

**Describe the solution you'd like**

I've seen some projects use `all` and the great majority use `es5`. I personally find the trailing comma in function arguments a bit strange, but I'm not completely against it. Anyway, `none` should not be used. 

I'd vote for `es5`

**Additional context**
https://prettier.io/docs/en/options.html#trailing-commas

**Comment by jgfidelis** [comment]
2

**Comment by gtkatakura** [comment]
3

**Comment by kevinch** [comment]
I'd use prettier's default.

**Comment by kaisermann** [comment]
Going with `es5` style. Very rarely we'll need them in function arguments, even more if we follow the rule of using an object for 2+ args.
